apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    editable: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: symphony
      defaultDatabase: symphony
      tlsSkipVerify: false
    secureJsonData:
      password: symphony
